<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinSightAPI.Application\FinSightAPI.Application.csproj" />
    <ProjectReference Include="..\FinSightAPI.Infrastructure\FinSightAPI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
